desc "Run all unit tests"
lane :tests do
  scan(
    workspace: "Example/AssertLayout.xcworkspace",
    configuration: "Debug",
    scheme: "AssertLayout-Example",
    clean: true,
    devices: ["iPhone 8"]
  )
end