desc "Run all unit tests"
lane :tests do
  scan(
    workspace: "Example/AssertLayout.xcworkspace",
    configuration: "Debug",
    scheme: "AssertLayout-Example",
    clean: true,
    devices: ["iPhone 8"]
  )
end

desc "Linting"
lane :lint do
  swiftlint(
      mode: :lint,
      config_file: "Example/.swiftlint.yml",
      strict: true,
      executable: "Example/Pods/SwiftLint/swiftlint"
  )
end